package dev.aarso.diagnostics.core

import dev.aarso.diagnostics.core.Stats.f
import dev.aarso.diagnostics.core.Stats.grp

/**
 * Renders a [Report] to the one file that leaves the device.
 *
 * The reader is assumed to be a language model with no memory of the run, so:
 *  - every section is preceded by a stable `<!-- diag:section=… -->` marker locatable by exact
 *    string even when the prose around it changes;
 *  - every number carries its unit and, where judged, the threshold that judged it;
 *  - caveats print ABOVE the data, so a reader who stops early has seen the reasons to distrust the
 *    numbers before seeing the numbers;
 *  - invariants print above the thresholds, because a violated structural claim outranks a missed
 *    percentile and should be the first thing read;
 *  - unmeasured things are listed explicitly, so absent never reads as zero.
 *
 * Output is deterministic for a given Report: same input, same bytes.
 */
class MarkdownReporter(
    private val profile: Profile,
    private val redactor: Redactor = Redactor.default(),
) {

    fun render(r: Report): String {
        val j = Judge.judge(r, profile)

        // Body first, so payload rules can assert over what was actually written. A privacy rule
        // enforced by intention alone is not enforced — see PayloadRule.
        val body = StringBuilder(24 * 1024)
        context(body, r)
        for (s in r.series) series(body, s)
        trends(body, r)
        lifecycle(body, r)
        thermal(body, r)
        counters(body, r)
        logs(body, r)
        crash(body, r)
        notMeasured(body, r)

        val payload = profile.payloadRules.map { it.evaluate(body.toString()) }

        val out = StringBuilder(32 * 1024)
        out.line("<!-- diag:schema=${r.schema} -->")
        out.line("# Diagnostics report — ${r.app.applicationId.substringAfterLast('.')} " +
            "(`${r.profileId}` profile)")
        out.blank()
        summary(out, r, j, payload)
        invariants(out, j, payload)
        caveats(out, j)
        out.append(body)
        out.line("<!-- diag:section=end -->")
        out.line("---")
        out.line("Generated by `dev.aarso:diagnostics` schema `${r.schema}` · profile " +
            "`${r.profileId}` · debug build only · no network permission · written to device " +
            "storage and shared manually.")
        return out.toString()
    }

    // ------------------------------------------------------------------ summary

    private fun summary(sb: StringBuilder, r: Report, j: Judgement, payload: List<InvariantResult>) {
        val all = j.invariants + payload
        sb.marker("summary")
        sb.line("## Summary")
        sb.blank()
        val fails = j.count(Grade.FAIL) + payload.count { it.grade == Grade.FAIL }
        val warns = j.count(Grade.WARN) + payload.count { it.grade == Grade.WARN }
        val passes = j.count(Grade.PASS) + payload.count { it.grade == Grade.PASS }
        val nas = j.count(Grade.NA) + payload.count { it.grade == Grade.NA }
        val overall = when {
            fails > 0 -> Grade.FAIL; warns > 0 -> Grade.WARN; passes > 0 -> Grade.PASS
            else -> Grade.NA
        }
        sb.line("**Overall: ${overall.chip}** — $fails fail, $warns warn, $passes pass, " +
            "$nas not evaluated")
        sb.line("**Profile: `${r.profileId}`** — ${r.profileTitle}")
        val reasons = j.caveats.count { it.downgrades }
        sb.line("**Confidence: ${j.confidence}** — " +
            if (reasons == 0) "no conditions found that would undermine these numbers."
            else "$reasons condition${if (reasons == 1) "" else "s"} may undermine these numbers; " +
                "see caveats before drawing conclusions.")
        sb.blank()

        val broken = all.filter { it.grade == Grade.FAIL || it.grade == Grade.WARN }
        if (broken.isNotEmpty()) {
            sb.line("**Invariants violated — read these first.** A broken structural claim outranks " +
                "any percentile: it is a defect, not a degradation.")
            sb.blank()
            for (v in broken) sb.line("- ${v.grade.chip} ${v.invariant.statement} " +
                "*(observed: ${v.observed})*")
            sb.blank()
        }

        sb.line("| Metric | Value | Threshold | Verdict |")
        sb.line("|---|---|---|---|")
        for (l in j.lines) sb.line("| ${l.metric} | ${l.value} | ${l.threshold} | ${l.grade.chip} |")
        sb.blank()

        val findings = Findings.derive(r, j)
        if (findings.isNotEmpty()) {
            sb.line("Derived findings (rule-based, not narrative — each states the rule it came from):")
            sb.blank()
            for (fn in findings) sb.line("- $fn")
            sb.blank()
        }
    }

    // ------------------------------------------------------------------ invariants

    private fun invariants(sb: StringBuilder, j: Judgement, payload: List<InvariantResult>) {
        sb.marker("invariants")
        sb.line("## Invariants")
        sb.blank()
        val all = j.invariants + payload
        if (all.isEmpty()) {
            sb.line("Profile `${profile.id}` declares no invariants.")
            sb.blank(); return
        }
        sb.line("Structural claims that must hold for this app type. These catch what thresholds " +
            "cannot — a delegate that silently fell back, a draw loop that never stopped, a " +
            "privacy claim that stopped being true. **Not evaluated is not the same as passing.**")
        sb.blank()
        sb.line("| Claim | Observed | Verdict |")
        sb.line("|---|---|---|")
        for (v in all) sb.line("| ${v.invariant.statement} | ${v.observed} | ${v.grade.chip} |")
        sb.blank()
        val explain = all.filter { it.grade != Grade.PASS }
        if (explain.isNotEmpty()) {
            for (v in explain) {
                sb.line("**${v.grade.chip} — ${v.invariant.statement}** (`${v.invariant.id}`)")
                sb.line(v.invariant.rationale)
                sb.blank()
            }
        }
    }

    // ------------------------------------------------------------------ caveats

    private fun caveats(sb: StringBuilder, j: Judgement) {
        sb.marker("caveats")
        sb.line("## Caveats — read before the numbers")
        sb.blank()
        j.caveats.forEachIndexed { i, c -> sb.line("${i + 1}. ${c.text}") }
        sb.blank()
        if (profile.notes.isNotEmpty()) {
            sb.line("Profile notes for `${profile.id}`:")
            sb.blank()
            for (n in profile.notes) sb.line("- $n")
            sb.blank()
        }
    }

    // ------------------------------------------------------------------ context

    private fun context(sb: StringBuilder, r: Report) {
        sb.marker("context")
        sb.line("## Context")
        sb.blank()
        val d = r.device
        sb.line("**Session** `${r.session.id}` · label `${r.session.label?.let { redactor.redact(it) } ?: "—"}` · started " +
            "${r.session.startedAtIso} · duration ${f(r.session.durationSec, 1)} s · trigger " +
            "`${r.session.trigger.name.lowercase().replace('_', '-')}`" +
            if (r.session.recovered) " · **recovered from journal**" else "")
        if (r.session.attributes.isNotEmpty()) {
            sb.blank()
            sb.line("**Attributes** " + r.session.attributes.entries.sortedBy { it.key }
                .joinToString(" · ") { "`${it.key}=${redactor.redact(it.value)}`" })
        }
        sb.blank()
        sb.line("**App** `${r.app.applicationId}` ${r.app.versionName} (${r.app.versionCode}) · " +
            "buildType `${r.app.buildType}` · debuggable ${r.app.debuggable}" +
            (r.app.gitSha?.let { " · git `$it`${if (r.app.gitDirty) " (dirty)" else ""}" } ?: ""))
        sb.blank()
        sb.line("**Device** ${d.model} (${d.manufacturer} ${d.codename}) · SoC " +
            "`${d.soc ?: "unknown"}` · Android ${d.androidRelease} (API ${d.apiLevel}) · " +
            "${d.abis.joinToString(", ")}")
        sb.line("RAM ${grp(d.totalRamMb)} MB total / ${grp(d.availRamMbAtStart)} MB available at " +
            "session start · rooted ${d.rooted}")
        sb.line("Display ${d.widthPx} × ${d.heightPx} · ${d.densityDpi} dpi · refresh " +
            "**${f(d.refreshHz, 1)} Hz** (panel max ${f(d.panelMaxHz, 1)} Hz) → vsync budget " +
            "**${f(d.budgetMs)} ms**")
        sb.blank()

        if (r.facts.isNotEmpty()) {
            sb.line("### Environment facts")
            sb.blank()
            sb.line("Discrete facts the invariants assert over. A fact that silently changed value " +
                "is the usual cause of a regression no timing metric explains.")
            sb.blank()
            sb.line("| Fact | Value |")
            sb.line("|---|---|")
            for (fact in r.facts.sortedBy { it.key })
                sb.line("| `${fact.key}` | ${redactor.redact(fact.value)}" +
                    "${fact.note?.let { " — $it" } ?: ""} |")
            sb.blank()
        }
    }

    // ------------------------------------------------------------------ series

    private fun series(sb: StringBuilder, s: SeriesReport) {
        val spec = s.spec
        sb.marker("series.${spec.id}")
        sb.line("## ${spec.title}  ·  `${spec.id}`")
        sb.blank()

        if (!spec.resolved) {
            sb.line("**Budget unresolved** — the source never supplied one, so these observations " +
                "are reported without judgement. Assuming a budget would be worse than admitting " +
                "there isn't one.")
            sb.blank()
        }
        if (s.whole.count == 0) {
            sb.line("No observations collected.")
            sb.blank(); return
        }

        sb.line("${grp(s.whole.count)} observations over ${f(s.durationSec, 1)} s · " +
            "${f(s.rate, 1)}/s · budget **${spec.budgetLabel}**")
        sb.blank()
        sb.line("| | p50 | p90 | p95 | p99 | max | mean |")
        sb.line("|---|---|---|---|---|---|---|")
        sb.statsRow("Whole session", s.whole)
        for (w in s.windows) sb.statsRow(w.label, w.stats)
        sb.blank()

        if (spec.resolved) {
            sb.line("${spec.overrunWord.replaceFirstChar { it.uppercase() }} " +
                "${spec.overrunRule}: **${grp(s.whole.overrunCount)} / " +
                "${grp(s.whole.count)} = ${f(s.whole.overrunRatePct)} %**")
            if (spec.severeMs != null) sb.line(
                "${spec.severeWord.replaceFirstChar { it.uppercase() }} " +
                    "(> ${f(spec.severeMs, 0)} ms): **${s.whole.severeCount}**")
            sb.blank()
        }

        if (s.buckets.isNotEmpty()) {
            sb.line("### By ${spec.bucketLabel ?: "bucket"}")
            sb.blank()
            sb.line("| ${spec.bucketLabel ?: "Bucket"} | n | ${spec.overrunWord} rate | p95 | p99 | first |")
            sb.line("|---|---|---|---|---|---|")
            for (b in s.buckets) sb.line("| ${redactor.redact(b.bucket)} | ${grp(b.stats.count)} | " +
                "${f(b.stats.overrunRatePct)} % | ${f(b.stats.p95)} ms | ${f(b.stats.p99)} ms | " +
                "${b.firstMs?.let { "${f(it, 0)} ms" } ?: "—"} |")
            sb.blank()
        }

        if (s.phaseMeans.isNotEmpty()) {
            sb.line("### Phase means over the worst non-${spec.severeWord} observations")
            sb.blank()
            val order = spec.phaseOrder.ifEmpty { s.phaseMeans.keys.sorted() }
            sb.line("| Phase | mean |")
            sb.line("|---|---|")
            for (k in order) s.phaseMeans[k]?.let { sb.line("| $k | ${f(it, 1)} ms |") }
            sb.blank()
            sb.line("Severe observations are excluded here and reported individually — one outlier " +
                "otherwise rewrites the attribution for everything else.")
            sb.blank()
        }

        if (s.worst.isNotEmpty()) {
            sb.line("### ${s.worst.size} worst observations")
            sb.blank()
            val phases = spec.phaseOrder.ifEmpty {
                s.worst.flatMap { it.phases.keys }.distinct().sorted() }
            sb.line("| # | t (s) | value | " + phases.joinToString(" | ") + " | " +
                "${spec.bucketLabel ?: "bucket"} |")
            sb.line("|---|---|---|" + phases.joinToString("") { "---|" } + "---|")
            s.worst.forEachIndexed { i, o ->
                sb.line("| ${i + 1} | ${f(o.tSec)} | ${f(o.valueMs, 1)} | " +
                    phases.joinToString(" | ") { f(o.phases[it] ?: 0.0, 1) } +
                    " | ${o.bucket?.let { redactor.redact(it) } ?: "—"} |")
            }
            sb.blank()
            sb.line("All times in ms.")
            sb.blank()
        }
    }

    private fun StringBuilder.statsRow(label: String, s: SeriesStats) = line(
        "| $label | ${f(s.p50)} ms | ${f(s.p90)} ms | ${f(s.p95)} ms | ${f(s.p99)} ms | " +
            "${f(s.max, 1)} ms | ${f(s.mean)} ms |")

    // ------------------------------------------------------------------ trends

    private fun trends(sb: StringBuilder, r: Report) {
        if (r.trends.isEmpty()) return
        sb.marker("trends")
        sb.line("## Trends")
        sb.blank()
        for (g in r.trends) {
            sb.line("### ${g.title}")
            sb.blank()
            if (g.sampleCount > 0)
                sb.line("Sampled every ${g.sampleIntervalMs} ms · ${grp(g.sampleCount)} samples")
            sb.blank()
            sb.line("| | start | peak | end | slope | R² |")
            sb.line("|---|---|---|---|---|---|")
            for (s in g.series) sb.line("| ${s.name} | ${f(s.start, 1)} ${g.unit} | " +
                "${f(s.peak, 1)} ${g.unit} | ${f(s.end, 1)} ${g.unit} | " +
                "${if (s.slopePerMin >= 0) "+" else ""}${f(s.slopePerMin)} ${g.unit}/min | " +
                "${f(s.r2)} |")
            sb.blank()
            for (n in g.notes) sb.line(n)
            sb.line("A slope is treated as a finding only when R² ≥ ${f(g.minR2)}; steep-but-noisy " +
                "is reported as inconclusive rather than raised as a leak.")
            sb.blank()
        }
    }

    // ------------------------------------------------------------------ lifecycle

    private fun lifecycle(sb: StringBuilder, r: Report) {
        sb.marker("lifecycle")
        sb.line("## Lifecycle and start-up")
        sb.blank()
        val s = r.startup
        if (s?.coldToFirstFrameMs != null) {
            sb.line("**Cold start** (process start → first frame): " +
                "**${grp(s.coldToFirstFrameMs.toLong())} ms**")
            sb.blank()
            sb.line("| Phase | Δ | cumulative |")
            sb.line("|---|---|---|")
            for (p in s.phases) sb.line("| ${p.name} | ${f(p.deltaMs, 0)} ms | " +
                "${f(p.cumulativeMs, 0)} ms |")
            sb.blank()
            sb.line("**Warm start** ${s.warmMs?.let { "${f(it, 0)} ms" } ?: "not measured"} · " +
                "**hot start** ${s.hotMs?.let { "${f(it, 0)} ms" } ?: "not measured"}")
        } else {
            sb.line("Cold start not measured — either not applicable to this profile " +
                "(`${r.profileId}`) or the tracker attached too late to see the first frame.")
        }
        sb.blank()

        if (r.spans.isNotEmpty()) {
            sb.line("### Custom spans")
            sb.blank()
            sb.line("| Span | n | p50 | p95 | max |")
            sb.line("|---|---|---|---|---|")
            for (sp in r.spans.sortedByDescending { it.count }) sb.line(
                "| `${redactor.redact(sp.name)}` | ${grp(sp.count)} | ${f(sp.p50Ms)} ms | " +
                    "${sp.p95Ms?.let { "${f(it)} ms" } ?: "—"} | ${f(sp.maxMs)} ms |")
            sb.blank()
            sb.line("`p95` is omitted below 20 observations — a p95 over fewer samples is not a p95.")
            sb.blank()
        }

        if (r.marks.isNotEmpty()) {
            sb.line("### Marks")
            sb.blank()
            sb.line("```")
            for (mk in r.marks.sortedBy { it.tSec })
                sb.line("t+%-9s %s%s".format(f(mk.tSec, 3), redactor.redact(mk.name),
                    if (mk.auto) "   (auto-emitted)" else ""))
            sb.line("```")
            sb.blank()
        }
    }

    // ------------------------------------------------------------------ thermal

    private fun thermal(sb: StringBuilder, r: Report) {
        sb.marker("thermal")
        sb.line("## Thermal and power")
        sb.blank()
        val p = r.power
        if (p == null) {
            sb.line("Not measured — thermal API unavailable below API 29, or collector disabled.")
            sb.blank(); return
        }
        if (p.windows.isEmpty()) sb.line("No thermal transitions recorded.")
        else {
            sb.line("| t | Status | Duration |")
            sb.line("|---|---|---|")
            for (w in p.windows) sb.line("| ${f(w.tSec, 0)} s | ${w.status} | " +
                "${f(w.durationSec, 0)} s |")
        }
        sb.blank()
        sb.line("Battery ${p.batteryStartPct?.let { "$it %" } ?: "—"} → " +
            "${p.batteryEndPct?.let { "$it %" } ?: "—"} · " +
            "${if (p.charging) "charging" else "discharging"} · power-save " +
            "${if (p.powerSave) "on" else "off"}")
        val drain = p.drainPctPerHour(r.session.durationSec, profile.minSessionSecForDrain)
        sb.line("Drain: " + (drain?.let { "${f(it, 1)} %/h" }
            ?: "not estimated — needs ≥ ${f(profile.minSessionSecForDrain, 0)} s on battery"))
        if (p.headroomStart != null || p.headroomEnd != null) sb.line(
            "Thermal headroom: ${p.headroomStart?.let { f(it) } ?: "—"} at start, " +
                "${p.headroomEnd?.let { f(it) } ?: "—"} at end.")
        sb.blank()
    }

    // ------------------------------------------------------------------ counters

    private fun counters(sb: StringBuilder, r: Report) {
        if (r.counters.isEmpty()) return
        sb.marker("counters")
        sb.line("## Counters")
        sb.blank()
        sb.line("| Counter | Value |")
        sb.line("|---|---|")
        for (c in r.counters.sortedBy { it.name })
            sb.line("| `${c.name}` | ${grp(c.value)}${c.note?.let { " — $it" } ?: ""} |")
        sb.blank()
    }

    // ------------------------------------------------------------------ logs

    private fun logs(sb: StringBuilder, r: Report) {
        sb.marker("logs")
        sb.line("## Log ring — last ${r.logs.size} of ${r.logRingCapacity} entries")
        sb.blank()
        if (r.logs.isEmpty()) { sb.line("Empty."); sb.blank(); return }
        sb.line("```")
        for (e in r.logs) {
            val red = redactor.redact(e)
            sb.line("${red.timeIso}  ${red.levelChar}  ${red.tag.padEnd(9)} ${red.message}")
        }
        sb.line("```")
        sb.blank()
        sb.line("Secrets, tokens, emails and user paths are replaced with typed placeholders such " +
            "as `<redacted:token>` before the file is written.")
        sb.blank()
    }

    // ------------------------------------------------------------------ crash

    private fun crash(sb: StringBuilder, r: Report) {
        sb.marker("crash")
        sb.line("## Crash link")
        sb.blank()
        val c = r.crash
        if (c == null) {
            sb.line("No crash record found. `:crash-recovery` module " +
                if (r.crashModulePresent) "present, last-crash file absent."
                else "not present in this build.")
            sb.blank(); return
        }
        sb.line("Last crash from `${c.moduleName}`, occurred ${c.occurredAtIso}:")
        sb.blank()
        sb.line("```")
        sb.line(redactor.redact(c.throwable))
        for (fr in c.topFrames) sb.line("    at ${redactor.redact(fr)}")
        sb.line("```")
        sb.blank()
        sb.line("The sections above cover the window preceding this crash — that pairing is the " +
            "main reason this module reads the crash file at export.")
        sb.blank()
    }

    // ------------------------------------------------------------------ not measured

    private fun notMeasured(sb: StringBuilder, r: Report) {
        sb.marker("notmeasured")
        sb.line("## Not measured")
        sb.blank()
        if (r.notMeasured.isEmpty()) sb.line("Everything profile `${r.profileId}` declares was collected.")
        else for (n in r.notMeasured) sb.line("${n.what} — ${n.why}.")
        sb.blank()
        sb.line("*Absent because it was not collected — not because it was zero.*")
        sb.blank()
    }

    // ------------------------------------------------------------------ helpers

    private fun StringBuilder.line(s: String) { append(s).append('\n') }
    private fun StringBuilder.blank() { append('\n') }
    private fun StringBuilder.marker(name: String) { line("<!-- diag:section=$name -->") }
}

/**
 * Deterministic, rule-based observations. Not narrative analysis — the module cannot write that and
 * should not pretend to. Each finding names the rule that produced it so a reader can check the
 * reasoning rather than trust it.
 *
 * Every rule here is source-agnostic: it operates on a SeriesReport, so the phase-dominance rule
 * that localises a UI stutter to the draw phase equally localises a pipeline stall to inference.
 */
object Findings {

    fun derive(r: Report, j: Judgement): List<String> {
        val out = mutableListOf<String>()

        for (s in r.series) {
            val spec = s.spec
            if (s.whole.count == 0) continue

            // Severe observations reported individually, and excluded from the phase attribution.
            val severeMs = spec.severeMs
            if (severeMs != null) {
                for (sev in s.worst.filter { it.valueMs > severeMs }.take(2)) {
                    val ph = sev.phases.maxByOrNull { it.value }
                    out += "`${spec.id}`: ${spec.severeWord} observation at t+${Stats.f(sev.tSec)} s " +
                        "(${Stats.f(sev.valueMs, 1)} ms)" +
                        (ph?.let { " is **${it.key}**-dominated (${Stats.f(it.value, 1)} ms)" } ?: "") +
                        " — rule: anything over ${Stats.f(severeMs, 0)} ms is reported individually " +
                        "and excluded from the phase means, because one outlier otherwise rewrites them."
                }
            }

            // Phase dominance.
            if (s.phaseMeans.size >= 3) {
                val total = s.phaseMeans.values.sum()
                if (total > 0) {
                    val top = s.phaseMeans.entries.sortedByDescending { it.value }.take(2)
                    val share = top.sumOf { it.value } * 100.0 / total
                    if (share >= 55.0) out += "`${spec.id}`: worst observations are dominated by " +
                        "**${top[0].key}** and **${top[1].key}** (${Stats.f(share, 0)} % of phase " +
                        "time) — rule: top two phases ≥ 55 %."
                }
            }

            // Concentration in one bucket.
            val ranked = s.buckets.filter { it.stats.count >= 50 }
                .sortedByDescending { it.stats.overrunRatePct }
            if (ranked.size >= 2 && ranked[0].stats.overrunRatePct >= 2 * ranked[1].stats.overrunRatePct
                && ranked[0].stats.overrunRatePct > 0.0) {
                out += "`${spec.id}`: ${spec.overrunWord}s concentrate in " +
                    "**${ranked[0].bucket}** (${Stats.f(ranked[0].stats.overrunRatePct)} % vs " +
                    "${Stats.f(ranked[1].stats.overrunRatePct)} % next) — rule: worst " +
                    "${spec.bucketLabel?.lowercase() ?: "bucket"} ≥ 2× the next, which argues " +
                    "against a global cause."
            }

            // Does throttling explain the tail?
            val pre = s.windows.firstOrNull { it.label.contains("Pre", true) }?.stats
            if (pre != null && pre.count > 0 && spec.resolved) {
                val target = spec.budgetMs * spec.targets.p99BudgetMultipleGood
                if (pre.p99 > target) out += "`${spec.id}`: p99 exceeds target **before** any " +
                    "throttling (${Stats.f(pre.p99)} ms vs ${Stats.f(target, 1)} ms) — rule: " +
                    "thermal state does not fully explain the tail."
            }
        }

        // Which component owns a trend?
        for (g in r.trends) {
            val head = g.series.firstOrNull() ?: continue
            if (head.slopePerMin <= 0.1 || head.r2 < g.minR2) continue
            val comp = g.series.drop(1).maxByOrNull { it.slopePerMin }
            if (comp != null && comp.slopePerMin > 0.5 * head.slopePerMin) {
                out += "`${g.id}`: **${comp.name}** owns ${Stats.f(comp.slopePerMin)} of the " +
                    "${Stats.f(head.slopePerMin)} ${g.unit}/min total growth (R² " +
                    "${Stats.f(comp.r2)}) — rule: one component ≥ 50 % of total slope with a " +
                    "supporting fit."
            }
        }

        // Unevaluated invariants are a finding in their own right.
        val un = j.unevaluated
        if (un.isNotEmpty()) out += "${un.size} invariant(s) unevaluated — " +
            un.joinToString(", ") { "`${it.invariant.id}`" } + " — rule: missing evidence is " +
            "reported, never treated as a pass."

        if (j.confidence == Confidence.LOW) out += "Confidence is LOW — prefer re-running under " +
            "better conditions over acting on these numbers."

        return out
    }
}
